#!/usr/bin/env bash
# diff-gate.sh — Run baseline + candidate harness and diff the results.
# Called by the composite GitHub Action defined in action.yml.
set -euo pipefail

CONFIG="${INPUT_CONFIG:-ci/harness.yaml}"
BASELINE_REF="${INPUT_BASELINE_REF:-}"
FAIL_ON="${INPUT_FAIL_ON:-regressions}"
HARNESS_ARGS="${INPUT_HARNESS_ARGS:---skip-report --deterministic-artifacts}"
POST_COMMENT="${INPUT_COMMENT:-true}"

RUN_ROOT=".tmp/diff-gate"
BASELINE_DIR="${RUN_ROOT}/baseline"
CANDIDATE_DIR="${RUN_ROOT}/candidate"
DIFF_JSON="${RUN_ROOT}/diff-report.json"

# -------------------------------------------------------------------
# 1. Run baseline harness (on the PR base commit)
# -------------------------------------------------------------------
echo "::group::Baseline harness"
if [ -n "$BASELINE_REF" ]; then
  git stash --include-untracked -q || true
  git checkout "$BASELINE_REF" --quiet
fi

# shellcheck disable=SC2086
python -m insideLLMs.cli harness "$CONFIG" \
  --run-dir "$BASELINE_DIR" --overwrite $HARNESS_ARGS
baseline_records=$(wc -l < "${BASELINE_DIR}/records.jsonl")
echo "Baseline records: $baseline_records"

if [ -n "$BASELINE_REF" ]; then
  git checkout - --quiet
  git stash pop -q 2>/dev/null || true
fi
echo "::endgroup::"

# -------------------------------------------------------------------
# 2. Run candidate harness (on the PR head commit)
# -------------------------------------------------------------------
echo "::group::Candidate harness"
# shellcheck disable=SC2086
python -m insideLLMs.cli harness "$CONFIG" \
  --run-dir "$CANDIDATE_DIR" --overwrite $HARNESS_ARGS
candidate_records=$(wc -l < "${CANDIDATE_DIR}/records.jsonl")
echo "Candidate records: $candidate_records"
echo "::endgroup::"

# -------------------------------------------------------------------
# 3. Diff
# -------------------------------------------------------------------
echo "::group::Diff"
DIFF_FLAGS="--format json --output $DIFF_JSON"
case "$FAIL_ON" in
  regressions) DIFF_FLAGS="$DIFF_FLAGS --fail-on-regressions" ;;
  changes)     DIFF_FLAGS="$DIFF_FLAGS --fail-on-changes" ;;
  none)        ;;  # no fail flags
  *)           echo "::error::Unknown fail-on mode: $FAIL_ON"; exit 1 ;;
esac

diff_exit=0
# shellcheck disable=SC2086
python -m insideLLMs.cli diff "$BASELINE_DIR" "$CANDIDATE_DIR" $DIFF_FLAGS || diff_exit=$?
echo "Diff exit code: $diff_exit"
echo "::endgroup::"

# Export outputs for the composite action
echo "exit_code=$diff_exit" >> "$GITHUB_OUTPUT"
echo "diff_json=$DIFF_JSON"  >> "$GITHUB_OUTPUT"

# -------------------------------------------------------------------
# 4. Build a Markdown summary from the JSON report
# -------------------------------------------------------------------
build_comment() {
  python - "$DIFF_JSON" "$diff_exit" <<'PYEOF'
import json, sys, os
diff_path, exit_code = sys.argv[1], int(sys.argv[2])
with open(diff_path) as f:
    d = json.load(f)
c = d["counts"]
status = "PASS" if exit_code == 0 else "FAIL"
icon = "\u2705" if exit_code == 0 else "\u274c"
lines = [
    f"## {icon} insideLLMs Diff Gate — **{status}**",
    "",
    "| Metric | Count |",
    "|--------|------:|",
    f"| Common records | {c['common']} |",
    f"| Regressions | {c['regressions']} |",
    f"| Improvements | {c['improvements']} |",
    f"| Other changes | {c['other_changes']} |",
    f"| Only in baseline | {c['only_baseline']} |",
    f"| Only in candidate | {c['only_candidate']} |",
]
if c.get("trace_drifts"):
    lines.append(f"| Trace drifts | {c['trace_drifts']} |")
if c.get("trace_violation_increases"):
    lines.append(f"| Trace violation increases | {c['trace_violation_increases']} |")

if d.get("regressions"):
    lines += ["", "### Regressions", ""]
    for r in d["regressions"][:10]:
        label = r.get("label", {})
        detail = r.get("detail", r.get("kind", ""))
        lines.append(f"- **{label.get('model', '?')}** / {label.get('probe', '?')} / "
                      f"ex {label.get('example', '?')}: {detail}")
    if len(d["regressions"]) > 10:
        lines.append(f"- *... and {len(d['regressions']) - 10} more*")

if d.get("improvements"):
    lines += ["", "### Improvements", ""]
    for r in d["improvements"][:10]:
        label = r.get("label", {})
        detail = r.get("detail", r.get("kind", ""))
        lines.append(f"- **{label.get('model', '?')}** / {label.get('probe', '?')} / "
                      f"ex {label.get('example', '?')}: {detail}")
    if len(d["improvements"]) > 10:
        lines.append(f"- *... and {len(d['improvements']) - 10} more*")

lines += ["", f"<sub>Generated by insideLLMs diff-gate</sub>"]
print("\n".join(lines))
PYEOF
}

COMMENT_BODY=$(build_comment)

# Write to GitHub Actions step summary
echo "$COMMENT_BODY" >> "${GITHUB_STEP_SUMMARY:-/dev/null}"

# -------------------------------------------------------------------
# 5. Post PR comment (if enabled and in a PR context)
# -------------------------------------------------------------------
if [ "$POST_COMMENT" = "true" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
  PR_NUMBER="${PR_NUMBER:-}"
  # Try to detect PR number from the event payload
  if [ -z "$PR_NUMBER" ] && [ -f "${GITHUB_EVENT_PATH:-/dev/null}" ]; then
    PR_NUMBER=$(python -c "
import json, os
try:
    with open(os.environ.get('GITHUB_EVENT_PATH', '')) as f:
        print(json.load(f).get('pull_request', {}).get('number', ''))
except Exception:
    pass
" 2>/dev/null || true)
  fi

  if [ -n "$PR_NUMBER" ]; then
    echo "Posting comment to PR #$PR_NUMBER"
    # Delete previous diff-gate comments to avoid clutter
    gh api "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
      --paginate --jq '.[] | select(.body | contains("insideLLMs Diff Gate")) | .id' \
      2>/dev/null | while read -r cid; do
        gh api -X DELETE "repos/${GITHUB_REPOSITORY}/issues/comments/${cid}" 2>/dev/null || true
      done
    # Post new comment
    gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY" 2>/dev/null || \
      echo "::warning::Could not post PR comment (missing permissions?)"
  else
    echo "::notice::Not in a PR context — skipping comment"
  fi
fi

exit "$diff_exit"
