#!/usr/bin/env python3
"""Build markdown summary for insideLLMs pull-request diff comments."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

MARKER = "<!-- insidellms-diff-comment -->"


def _item_label(item: dict[str, Any]) -> str:
    label = item.get("label")
    if isinstance(label, dict):
        model = label.get("model", item.get("model_id", "unknown"))
        probe = label.get("probe", item.get("probe_id", "unknown"))
        example = label.get("example", item.get("example_id", "unknown"))
        return f"{model} | {probe} | example {example}"
    model = item.get("model_id", "unknown")
    probe = item.get("probe_id", "unknown")
    example = item.get("example_id", "unknown")
    return f"{model} | {probe} | example {example}"


def _item_detail(item: dict[str, Any]) -> str:
    detail = item.get("detail")
    if isinstance(detail, str) and detail:
        return detail
    kind = item.get("kind")
    if isinstance(kind, str) and kind:
        return kind
    return "changed"


def _render_section(
    lines: list[str], title: str, items: list[dict[str, Any]], *, limit: int
) -> None:
    lines.append(f"### {title} ({len(items)})")
    if not items:
        lines.append("- None")
        lines.append("")
        return
    for item in items[:limit]:
        lines.append(f"- `{_item_label(item)}`: {_item_detail(item)}")
    if len(items) > limit:
        lines.append(f"- ... and {len(items) - limit} more")
    lines.append("")


def build_comment(diff_payload: dict[str, Any], *, diff_exit_code: int, limit: int = 10) -> str:
    counts = diff_payload.get("counts", {}) if isinstance(diff_payload, dict) else {}
    regressions = diff_payload.get("regressions", [])
    improvements = diff_payload.get("improvements", [])
    changes = diff_payload.get("changes", [])
    only_baseline = diff_payload.get("only_baseline", [])
    only_candidate = diff_payload.get("only_candidate", [])
    trace_drifts = diff_payload.get("trace_drifts", [])
    trace_violation_increases = diff_payload.get("trace_violation_increases", [])
    error_message = diff_payload.get("error")

    lines: list[str] = [MARKER, "## insideLLMs Behavioural Diff"]
    if error_message:
        lines.append(f"Diff command error: `{error_message}` (exit code `{diff_exit_code}`)")
        return "\n".join(lines) + "\n"

    lines.extend(
        [
            "",
            f"- Exit code: `{diff_exit_code}`",
            f"- Baseline run dir: `{diff_payload.get('baseline', 'unknown')}`",
            f"- Candidate run dir: `{diff_payload.get('candidate', 'unknown')}`",
            "",
            "| Metric | Count |",
            "|---|---:|",
            f"| Common keys | {counts.get('common', 0)} |",
            f"| Regressions | {counts.get('regressions', 0)} |",
            f"| Improvements | {counts.get('improvements', 0)} |",
            f"| Other changes | {counts.get('other_changes', 0)} |",
            f"| Only baseline | {counts.get('only_baseline', 0)} |",
            f"| Only candidate | {counts.get('only_candidate', 0)} |",
            f"| Trace drifts | {counts.get('trace_drifts', 0)} |",
            f"| Trace violation increases | {counts.get('trace_violation_increases', 0)} |",
            "",
            "<details>",
            "<summary>Top changed records</summary>",
            "",
        ]
    )

    _render_section(lines, "Regressions", regressions, limit=limit)
    _render_section(lines, "Improvements", improvements, limit=limit)
    _render_section(lines, "Other changes", changes, limit=limit)
    _render_section(lines, "Only in baseline", only_baseline, limit=limit)
    _render_section(lines, "Only in candidate", only_candidate, limit=limit)
    _render_section(lines, "Trace drifts", trace_drifts, limit=limit)
    _render_section(lines, "Trace violation increases", trace_violation_increases, limit=limit)
    lines.extend(["</details>", "", "_Generated by `insideLLMs/action`._", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--diff-json", required=True, help="Path to diff.json output")
    parser.add_argument("--output", required=True, help="Path to write markdown comment")
    parser.add_argument("--diff-exit-code", type=int, default=0)
    parser.add_argument("--limit", type=int, default=10)
    args = parser.parse_args()

    diff_path = Path(args.diff_json)
    output_path = Path(args.output)

    try:
        payload = json.loads(diff_path.read_text(encoding="utf-8"))
    except Exception as exc:
        payload = {"error": f"Unable to parse diff JSON: {exc}"}

    markdown = build_comment(payload, diff_exit_code=args.diff_exit_code, limit=args.limit)
    output_path.write_text(markdown, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
